#logging:
#    level:
#        org:
#            hibernate:
#                SQL: debug
#                orm:
#                    jdbc:
#                        bind: trace
#        root: warn
spring:
    application:
        name: HotelManagementSystem
    datasource:
        password: hmsadmin
        url: jdbc:mysql://localhost:3306/hotel_management
        username: hmsadmin
    main:
        banner-mode: 'off'
    jpa:
        show-sql: true